### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by cuhte3** [yenom/BitcoinKit#145]
Any advice where to start?

**Comment by akifuj** [comment]
@cuhte3 

We do not plan to support OSX, because this library requires Xcode9, which needs macOS.
Thanks!

**Comment by kkishikawa-folio** [comment]
@cuhte3 I think BitcoinKit can run on macOS with just small fix.

Because  BitcoinKit doesn't have UIKit dependency. I quick searched "UIKit" in the repository, it is found only example code (except BitcoinKit.h 😅 It should be fixed to `import Foundation`). 

So, the small fix is:
- Build dependency (OpenSSL and secp256k1) for macOS architecture
- Add macOS build configuration to BitcoinKit
- Fix `import UIKit` to `import Foundation` in `BitcoinKit.h` 

Build it.
